### 동물 분류
https://drive.usercontent.google.com/download?id=1_d8RcCM21XneorFe_m4939erMkCnccS1&export=download&authuser=0

In [4]:
with open('./datasets/animals/translate.py') as f:
    content = f.readline()
    #문자열 안의 요소는 eval로 풀어야함 dict로 하면 안됨
    contents1 = eval(content[content.index('{'):content.index('}') + 1])
    contents2 = {v : k for k, v in contents1.items()}

print(contents1, contents2, sep='\n')

{'cane': 'dog', 'cavallo': 'horse', 'elefante': 'elephant', 'farfalla': 'butterfly', 'gallina': 'chicken', 'gatto': 'cat', 'mucca': 'cow', 'pecora': 'sheep', 'scoiattolo': 'squirrel', 'dog': 'cane', 'elephant': 'elefante', 'butterfly': 'farfalla', 'chicken': 'gallina', 'cat': 'gatto', 'cow': 'mucca', 'spider': 'ragno', 'squirrel': 'scoiattolo'}
{'dog': 'cane', 'horse': 'cavallo', 'elephant': 'elefante', 'butterfly': 'farfalla', 'chicken': 'gallina', 'cat': 'gatto', 'cow': 'mucca', 'sheep': 'pecora', 'squirrel': 'scoiattolo', 'cane': 'dog', 'elefante': 'elephant', 'farfalla': 'butterfly', 'gallina': 'chicken', 'gatto': 'cat', 'mucca': 'cow', 'ragno': 'spider', 'scoiattolo': 'squirrel'}


In [12]:
from glob import glob
import os

root = './datasets/animals/original'

directories = glob(os.path.join(root, '*'))

for directory in directories:
    try:
        print(directory[directory.rindex('\\') + 1:])
        os.rename(directory, os.path.join(root, contents1[directory[directory.rindex('\\') + 1:]]))
    except KeyError as e:
         os.rename(directory, os.path.join(root, contents2[directory[directory.rindex('\\') + 1:]]))

cane
cavallo
elefante
farfalla
gallina
gatto
mucca
pecora
ragno
squirrel


In [15]:
root = './datasets/animals/original'

directories = glob(os.path.join(root, '*'))
print(directories)
directory_names = []
for directory in directories:
    directory_names.append(directory[directory.rindex('\\') + 1:])

print(directory_names)

['./datasets/animals/original\\butterfly', './datasets/animals/original\\cat', './datasets/animals/original\\chicken', './datasets/animals/original\\cow', './datasets/animals/original\\dog', './datasets/animals/original\\elephant', './datasets/animals/original\\horse', './datasets/animals/original\\sheep', './datasets/animals/original\\spider', './datasets/animals/original\\squirrel']
['butterfly', 'cat', 'chicken', 'cow', 'dog', 'elephant', 'horse', 'sheep', 'spider', 'squirrel']


In [17]:
root = './datasets/animals/original/'

for name in directory_names:
    for i, file_name in enumerate(os.listdir(os.path.join(root, name))):
        old_file = os.path.join(root + name + '/', file_name)
        new_file = os.path.join(root + name + '/', name + str(i + 1) + '.png')

        os.rename(old_file, new_file)

In [19]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

image_data_generator = ImageDataGenerator(rescale=1./255)

generator = image_data_generator.flow_from_directory(root, target_size = (150, 150), batch_size=32, class_mode='categorical')
print(generator.class_indices)

Found 26179 images belonging to 10 classes.
{'butterfly': 0, 'cat': 1, 'chicken': 2, 'cow': 3, 'dog': 4, 'elephant': 5, 'horse': 6, 'sheep': 7, 'spider': 8, 'squirrel': 9}


In [20]:
import pandas as pd

a_df = pd.DataFrame({'file_paths': generator.filepaths, 'targets': generator.classes})
a_df

file_paths  targets
0      ./datasets/animals/original/butterfly\butterfl...        0
1      ./datasets/animals/original/butterfly\butterfl...        0
2      ./datasets/animals/original/butterfly\butterfl...        0
3      ./datasets/animals/original/butterfly\butterfl...        0
4      ./datasets/animals/original/butterfly\butterfl...        0
...                                                  ...      ...
26174  ./datasets/animals/original/squirrel\squirrel9...        9
26175  ./datasets/animals/original/squirrel\squirrel9...        9
26176  ./datasets/animals/original/squirrel\squirrel9...        9
26177  ./datasets/animals/original/squirrel\squirrel9...        9
26178  ./datasets/animals/original/squirrel\squirrel9...        9

[26179 rows x 2 columns]

In [21]:
a_df.loc[:,  'file_paths'] = a_df.file_paths.apply(lambda x: x.replace('\\', '/'))
a_df

file_paths  targets
0      ./datasets/animals/original/butterfly/butterfl...        0
1      ./datasets/animals/original/butterfly/butterfl...        0
2      ./datasets/animals/original/butterfly/butterfl...        0
3      ./datasets/animals/original/butterfly/butterfl...        0
4      ./datasets/animals/original/butterfly/butterfl...        0
...                                                  ...      ...
26174  ./datasets/animals/original/squirrel/squirrel9...        9
26175  ./datasets/animals/original/squirrel/squirrel9...        9
26176  ./datasets/animals/original/squirrel/squirrel9...        9
26177  ./datasets/animals/original/squirrel/squirrel9...        9
26178  ./datasets/animals/original/squirrel/squirrel9...        9

[26179 rows x 2 columns]

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
train_test_split(a_df.file_paths, a_df.targets, stratify=a_df.targets, test_size=0.2, random_state=124)

print(y_train.value_counts())
print(y_test.value_counts())

targets
4    3890
8    3857
2    2478
6    2098
0    1690
3    1493
9    1490
7    1456
1    1334
5    1157
Name: count, dtype: int64
targets
4    973
8    964
2    620
6    525
0    422
3    373
9    372
7    364
1    334
5    289
Name: count, dtype: int64


In [24]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val= \
train_test_split(X_train, y_train, stratify=y_train, test_size=0.2, random_state=124)

print(y_train.value_counts())
print(y_val.value_counts())

targets
4    3112
8    3086
2    1982
6    1678
0    1352
3    1194
9    1192
7    1165
1    1067
5     926
Name: count, dtype: int64
targets
4    778
8    771
2    496
6    420
0    338
3    299
9    298
7    291
1    267
5    231
Name: count, dtype: int64


In [33]:
import shutil

root = './datasets/animals/'

for file_path in X_train:
    print(file_path[len(root+ 'original/'): file_path.rindex('/')])
    animal_dir = file_path[len(root+ 'original/'): file_path.rindex('/')]
    destination = os.path.join(root, 'train/' + animal_dir)

    if not os.path.exists(destination):
        os.makedirs(destination)

    shutil.copy2(file_path, destination)

butterfly
cow
horse
dog
dog
cow
butterfly
spider
cat
squirrel
dog
chicken
cat
dog
squirrel
dog
cow
dog
dog
dog
sheep
elephant
squirrel
chicken
cat
dog
dog
sheep
spider
chicken
cat
butterfly
spider
dog
chicken
spider
dog
cat
squirrel
horse
cow
chicken
dog
chicken
butterfly
dog
cow
butterfly
squirrel
butterfly
dog
horse
squirrel
horse
cow
elephant
spider
dog
cat
dog
squirrel
sheep
horse
elephant
chicken
horse
spider
dog
sheep
butterfly
chicken
spider
sheep
chicken
horse
cow
elephant
chicken
spider
butterfly
horse
cat
spider
cow
sheep
dog
dog
spider
butterfly
squirrel
chicken
dog
chicken
elephant
spider
spider
spider
sheep
elephant
squirrel
horse
squirrel
squirrel
dog
dog
sheep
horse
dog
spider
butterfly
dog
squirrel
dog
horse
butterfly
spider
dog
sheep
squirrel
sheep
sheep
elephant
spider
horse
sheep
spider
horse
dog
elephant
cow
horse
butterfly
spider
cow
dog
squirrel
sheep
dog
sheep
dog
spider
squirrel
sheep
sheep
dog
squirrel
horse
dog
sheep
squirrel
butterfly
squirrel
spider
chicken


In [34]:
import shutil

root = './datasets/animals/'

for file_path in X_val:
    print(file_path[len(root+ 'original/'): file_path.rindex('/')])
    animal_dir = file_path[len(root+ 'original/'): file_path.rindex('/')]
    destination = os.path.join(root, 'validation/' + animal_dir)

    if not os.path.exists(destination):
        os.makedirs(destination)

    shutil.copy2(file_path, destination)

cow
spider
chicken
dog
spider
spider
dog
dog
cat
chicken
butterfly
dog
butterfly
dog
cat
chicken
elephant
cow
sheep
butterfly
spider
cow
spider
chicken
elephant
sheep
horse
spider
butterfly
spider
sheep
spider
dog
chicken
sheep
dog
spider
dog
spider
chicken
butterfly
dog
horse
butterfly
spider
horse
elephant
squirrel
chicken
butterfly
chicken
horse
squirrel
cat
cat
sheep
squirrel
butterfly
squirrel
squirrel
dog
spider
dog
spider
dog
dog
dog
chicken
sheep
butterfly
spider
dog
spider
spider
spider
chicken
butterfly
sheep
spider
butterfly
horse
spider
dog
cow
butterfly
cow
dog
cat
spider
cow
cow
dog
dog
butterfly
horse
spider
squirrel
horse
cow
horse
cat
cow
cat
sheep
butterfly
dog
horse
cow
spider
dog
dog
spider
spider
chicken
spider
spider
dog
sheep
dog
horse
cat
horse
elephant
spider
sheep
chicken
cat
squirrel
spider
horse
dog
chicken
spider
cow
cow
chicken
dog
chicken
chicken
horse
cat
squirrel
chicken
dog
squirrel
dog
dog
chicken
spider
butterfly
chicken
horse
cow
dog
chicken
horse
s

In [35]:
import shutil

root = './datasets/animals/'

for file_path in X_test:
    print(file_path[len(root+ 'original/'): file_path.rindex('/')])
    animal_dir = file_path[len(root+ 'original/'): file_path.rindex('/')]
    destination = os.path.join(root, 'test/' + animal_dir)

    if not os.path.exists(destination):
        os.makedirs(destination)

    shutil.copy2(file_path, destination)

squirrel
elephant
horse
dog
sheep
spider
cow
spider
cow
butterfly
dog
spider
spider
chicken
elephant
cow
spider
spider
dog
spider
elephant
sheep
spider
dog
dog
butterfly
cow
spider
dog
chicken
sheep
chicken
sheep
cow
butterfly
butterfly
dog
dog
dog
squirrel
dog
sheep
horse
butterfly
horse
spider
chicken
dog
squirrel
spider
spider
spider
butterfly
dog
elephant
horse
butterfly
chicken
squirrel
elephant
butterfly
elephant
chicken
spider
squirrel
spider
butterfly
cat
sheep
chicken
dog
spider
squirrel
dog
butterfly
spider
elephant
cat
cow
spider
butterfly
horse
horse
spider
dog
dog
dog
sheep
cow
horse
butterfly
dog
dog
dog
spider
dog
butterfly
spider
horse
chicken
chicken
spider
spider
dog
sheep
spider
dog
cow
elephant
squirrel
spider
horse
squirrel
butterfly
dog
chicken
spider
sheep
elephant
dog
cow
dog
spider
dog
dog
sheep
horse
horse
dog
sheep
chicken
cat
horse
chicken
butterfly
spider
cat
dog
horse
butterfly
spider
butterfly
cow
butterfly
horse
elephant
squirrel
horse
spider
chicken
cat

In [48]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_dir = './datasets/animals/train'
test_dir = './datasets/animals/test'
val_dir = './datasets/animals/validation'

image_data_generator = ImageDataGenerator()

train_generator = image_data_generator.flow_from_directory(
    train_dir,
    target_size= (150, 150),
    batch_size=32,
    class_mode='categorical'
)

validation_generator = image_data_generator.flow_from_directory(
    val_dir,
    target_size= (150, 150),
    batch_size=32,
    class_mode='categorical'
)

test_generator = image_data_generator.flow_from_directory(
    test_dir,
    target_size= (150, 150),
    batch_size=32,
    class_mode='categorical'
)

Found 16754 images belonging to 10 classes.
Found 4189 images belonging to 10 classes.
Found 5236 images belonging to 10 classes.


In [49]:
train_images, train_labels = next(train_generator)
print(train_images.shape, train_labels.shape)

(32, 150, 150, 3) (32, 10)


In [50]:
test_images, test_labels = next(test_generator)

In [51]:
val_images, val_labels = next(validation_generator)

In [52]:
print(train_images)

[[[[212. 199. 190.]
   [216. 203. 194.]
   [216. 202. 193.]
   ...
   [190. 158. 119.]
   [192. 155. 111.]
   [179. 134.  93.]]

  [[211. 201. 192.]
   [213. 203. 194.]
   [216. 203. 195.]
   ...
   [186. 152. 117.]
   [180. 146. 101.]
   [161. 121.  72.]]

  [[215. 206. 199.]
   [213. 204. 195.]
   [213. 203. 194.]
   ...
   [180. 146. 108.]
   [183. 149. 111.]
   [187. 153. 116.]]

  ...

  [[201. 169. 158.]
   [186. 151. 132.]
   [188. 172. 173.]
   ...
   [154. 125.  93.]
   [157. 135. 114.]
   [174. 157. 141.]]

  [[187. 181. 183.]
   [188. 182. 186.]
   [188. 191. 210.]
   ...
   [155. 126.  92.]
   [161. 137. 113.]
   [151. 130. 109.]]

  [[191. 159. 136.]
   [185. 162. 146.]
   [204. 195. 186.]
   ...
   [168. 138. 102.]
   [170. 142. 118.]
   [156. 131. 109.]]]


 [[[210. 229. 255.]
   [205. 224. 254.]
   [207. 226. 255.]
   ...
   [145. 130.  99.]
   [120. 105.  74.]
   [121. 106.  75.]]

  [[205. 224. 254.]
   [200. 219. 249.]
   [202. 221. 251.]
   ...
   [157. 142. 109.]
 

In [46]:
import numpy as np

def get_preprocessed_data(images, targets):
    images = np.array(images / 255.0, dtype=np.float32)
    targets = np.array(targets, dtype=np.float32)

    return images, targets

train_images, train_targets = get_preprocessed_data(train_images, train_labels)
val_images, val_targets = get_preprocessed_data(val_images, val_labels)
test_images, test_targets = get_preprocessed_data(test_images, test_labels)

In [53]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Flatten, Dense, Conv2D, MaxPooling2D, Activation, Dropout, GlobalAveragePooling2D, BatchNormalization
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping
from tensorflow.keras.regularizers import l1, l2

IMAGE_SIZE = 150

input_tensor = Input(shape=(IMAGE_SIZE, IMAGE_SIZE, 3))

# alpha를 크게 할 수록 Weight값을 작게 만들어서 과적합을 개선할 수 있고
# alpha를 작게 할 수록 Weight의 값이 커지지만, 어느 정도 상쇄하므로 과소적합을 개선할 수 있다.
x = Conv2D(filters=64, kernel_size=3, padding='same', kernel_initializer='he_normal')(input_tensor)
x = BatchNormalization()(x)
x = Activation('relu')(x)

x = Conv2D(filters=64, kernel_size=3, padding='same', kernel_initializer='he_normal')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling2D(2)(x)

x = Conv2D(filters=128, kernel_size=3, padding='same', kernel_initializer='he_normal')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)

x = Conv2D(filters=128, kernel_size=3, padding='same',  kernel_initializer='he_normal')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling2D(2)(x)

x = Conv2D(filters=256, kernel_size=3, padding='same', kernel_initializer='he_normal')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)

x = Conv2D(filters=256, kernel_size=3, padding='same', kernel_initializer='he_normal')(x)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling2D(2)(x)

x = GlobalAveragePooling2D()(x)
x = Dropout(rate=0.5)(x)
x = Dense(300, activation='relu',  kernel_initializer='he_normal')(x)
x = Dropout(rate=0.3)(x)
output = Dense(10, activation='softmax', kernel_initializer='glorot_normal')(x)

model = Model(inputs=input_tensor, outputs=output)
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 150, 150, 3)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 150, 150, 64)        │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_6                │ (None, 150, 150, 64)        │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_6 (Activation)            │ (None, 150, 150, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 150, 150, 64)        │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_7                │ (None, 150, 150, 64)        │             256 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_7 (Activation)            │ (None, 150, 150, 64)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 75, 75, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 75, 75, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_8                │ (None, 75, 75, 128)         │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_8 (Activation)            │ (None, 75, 75, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 75, 75, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_9                │ (None, 75, 75, 128)         │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_9 (Activation)            │ (None, 75, 75, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 37, 37, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_10 (Conv2D)                   │ (None, 37, 37, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_10               │ (None, 37, 37, 256)         │           1,024 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ activation_10 (Activation)           │ (None, 37, 37, 256)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_11 (Conv2D)                   │ (None, 37, 37, 256)         │         590,0

 Total params: 1,229,102 (4.69 MB)

 Trainable params: 1,227,310 (4.68 MB)

 Non-trainable params: 1,792 (7.00 KB)

In [54]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy

model.compile(optimizer=Adam(), loss=CategoricalCrossentropy(), metrics=['acc'])

In [55]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.callbacks import ModelCheckpoint

mcp_cb = ModelCheckpoint(
    filepath="./callback_files/weights.{epoch:03d}-{val_loss:.4f}-{acc:.4f}.weights.h5",
    monitor='val_loss',
    # 모든 epoch의 파일을 저장하지 않고 좋은 성능이라 판단될 경우만 저장할 때 True설정
    save_best_only=False,
    save_weights_only=True,
    mode='min'
)

rlr_cb = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.1,
    patience=2,
    mode='min'
)

ely_cb = EarlyStopping(
    monitor='val_loss',
    patience=3,
    mode='min'
)

history = model.fit(train_generator,
                    validation_data=validation_generator,
                    batch_size=32, epochs=20, callbacks=[mcp_cb, rlr_cb, ely_cb])

Epoch 1/20


C:\ProgramData\anaconda3\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


524/524 ━━━━━━━━━━━━━━━━━━━━ 623s 1s/step - acc: 0.2360 - loss: 2.2563 - val_acc: 0.2915 - val_loss: 1.9861 - learning_rate: 0.0010
Epoch 2/20
524/524 ━━━━━━━━━━━━━━━━━━━━ 669s 1s/step - acc: 0.3682 - loss: 1.7790 - val_acc: 0.4182 - val_loss: 1.6187 - learning_rate: 0.0010
Epoch 3/20
524/524 ━━━━━━━━━━━━━━━━━━━━ 597s 1s/step - acc: 0.4499 - loss: 1.5521 - val_acc: 0.4822 - val_loss: 1.4594 - learning_rate: 0.0010
Epoch 4/20
524/524 ━━━━━━━━━━━━━━━━━━━━ 568s 1s/step - acc: 0.4963 - loss: 1.4257 - val_acc: 0.4817 - val_loss: 1.5229 - learning_rate: 0.0010
Epoch 5/20
524/524 ━━━━━━━━━━━━━━━━━━━━ 602s 1s/step - acc: 0.5290 - loss: 1.3327 - val_acc: 0.5164 - val_loss: 1.3342 - learning_rate: 0.0010
Epoch 6/20
524/524 ━━━━━━━━━━━━━━━━━━━━ 595s 1s/step - acc: 0.5548 - loss: 1.2635 - val_acc: 0.5629 - val_loss: 1.2450 - learning_rate: 0.0010
Epoch 7/20
  2/524 ━━━━━━━━━━━━━━━━━━━━ 8:57 1s/step - acc: 0.5703 - loss: 1.2054 

KeyboardInterrupt: 

In [58]:
from tensorflow.keras.models import load_model

model.load_weights('./callback_files/weights.006-1.2450-0.5586.weights.h5')

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.callbacks import ModelCheckpoint

mcp_cb = ModelCheckpoint(
    filepath="./callback_files/weights.{epoch:03d}-{val_loss:.4f}-{acc:.4f}.weights.h5",
    monitor='val_loss',
    # 모든 epoch의 파일을 저장하지 않고 좋은 성능이라 판단될 경우만 저장할 때 True설정
    save_best_only=False,
    save_weights_only=True,
    mode='min'
)

rlr_cb = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.1,
    patience=2,
    mode='min'
)

ely_cb = EarlyStopping(
    monitor='val_loss',
    patience=3,
    mode='min'
)

history = model.fit(train_generator,
                    validation_data=validation_generator,
                    batch_size=32, epochs=20, callbacks=[mcp_cb, rlr_cb, ely_cb])

Epoch 1/20
524/524 ━━━━━━━━━━━━━━━━━━━━ 571s 1s/step - acc: 0.5821 - loss: 1.1963 - val_acc: 0.5514 - val_loss: 1.2933 - learning_rate: 0.0010
Epoch 2/20
  2/524 ━━━━━━━━━━━━━━━━━━━━ 9:07 1s/step - acc: 0.7109 - loss: 0.9668 

KeyboardInterrupt: 